version: '3.8'

services:
  sample-service:
    image: solcr/sample-api:nodejs
    container_name: sample-service
    ports:
      - 9000:80
    networks:
      - demo-kong-gateway

  sample-secret-service:
    image: solcr/sample-api-secret:nodejs
    container_name: sample-identity-service
    ports:
      - 9001:80
    networks:
      - demo-kong-gateway

  kong:
    image: kong:alpine
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DNS_ORDER=LAST,A,CNAME
    ports:
      - "8000:8000"
      - "127.0.0.1:8001:8001"
      - "8443:8443"
      - "127.0.0.1:8444:8444"
    volumes:
      - "./config:/usr/local/kong/declarative"
    networks:
      - demo-kong-gateway

networks:
  demo-kong-gateway:
