version: '3.8'

networks:
  kong-demo:


volumes:
  kong_data:
  konga_data:


services:
  # kong-database postgres
  kong-database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - kong-demo
    volumes:
      - kong_data:/var/lib/postgresql/data

  # kong migration
  kong-migration:
    image: kong:alpine
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure
    networks:
      - kong-demo

  # kong gateway
  kong-gateway:
    image: kong:alpine
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ACCSES_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - 8000:8000
      - 127.0.0.1:8001:8001
      - 8443:8443
      - 127.0.0.1:8444:8444
    restart: on-failure
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - kong-demo

  # sample-service nodejs
  api-sample-service:
    build:
      context: sample-service
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: on-failure
    networks:
      - kong-demo

  # kong database prepare
  konga-prepare:
    image: pantsel/konga
    depends_on:
      - kong-database
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
    restart: on-failure
    networks:
      - kong-demo

  # konga gui
  konga:
    image: pantsel/konga
    depends_on:
      - kong-database
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_DATABASE=konga_db
      - DB_USER=kong
      - DB_PASSWORD=kong
      - NODE_ENV=development
    restart: on-failure
    ports:
      - 1337:1337
    networks:
      - kong-demo
    volumes:
      - konga_data:/var/lib/postgresql/data
