version: '3.8'

services:
  # kong-database postgres
  kong-database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong-demo-nw

  # kong migration
  kong-migration:
    image: kong:alpine
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure
    networks:
      - kong-demo-nw

  # kong gateway
  kong-gateway:
    image: kong:alpine
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ACCSES_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_DNS_ORDER=LAST,A,CNAME
    ports:
      - 8000:8000
      - 127.0.0.1:8001:8001
      - 8443:8443
      - 127.0.0.1:8444:8444
    restart: on-failure
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - kong-demo-nw

  # kong database prepare
  konga-prepare:
    image: pantsel/konga
    depends_on:
      - kong-database
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
    restart: on-failure
    networks:
      - kong-demo-nw

  # konga gui
  konga:
    image: pantsel/konga
    depends_on:
      - kong-database
    environment:
      - DB_ADAPTER=postgres
      - DB_URI=postgresql://kong:kong@kong-database:5432/konga_db
    restart: on-failure
    ports:
      - 1337:1337
    networks:
      - kong-demo-nw
    volumes:
      - konga_data:/var/lib/postgresql/data

  # Api service
  sample-service:
    image: solcr/sample-api:nodejs
    ports:
      - 9000:80
    networks:
      - kong-demo-nw

  sample-identity-service:
    image: solcr/sample-api-secret:nodejs
    ports:
      - 9001:80
    networks:
      - kong-demo-nw

networks:
  kong-demo-nw:


volumes:
  kong_data:
  konga_data:
