version: '3,8'

services:
  nodejs-app:
    container_name: connanaka/swarm-test:nodejs
    build:
      context: ./node
      dockerfile: Dockerfile
    image: connanaka/swarm-test:nodejs

  php-app:
    container_name: connanaka/swarm-test:php
    build:
      context: ./php
      dockerfile: Dockerfile
    image: connanaka/swarm-test:php
