version: "3.8"

services:
  service1:
    image: solcr/swarm-test:php
    ports:
      - 8001:8001
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  service2:
    image: solcr/swarm-test:nodejs
    ports:
      - 8002:8022
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
