_format_version: "3.0"
_transform: true

services:
  - host: sample-service
    name: sample_api_service
    port: 80
    protocol: http
    routes:
      - name: PATH_GET_mocks
        protocols:
          - http
          - https
        methods:
          - GET
        paths:
          - /mocks
        plugins:
          - name: jwt
            enabled: true
            config:
              key_claim_name: kid
              claims_to_verify:
                - exp
        strip_path: true
      - name: PATH_POST_PUT_mocks
        protocols:
          - http
          - https
        methods:
          - POST
          - PUT
        paths:
          - /mocks

  - host: sample-identity-service
    name: sample_identity_api_service
    port: 80
    protocol: http
    routes:
      - name: path_identity
        protocols:
          - http
          - https
        paths:
          - /identity
        strip_path: true

plugins:
  - name: acme
    config:
      account_email: hungntsol77@gmail.com
      domains:
        - "*.localhost"
        - "*.host.docker.internal"
#  - name: jwt
#    service: sample_identity_api_service
#    enabled: true
#    config:
#      key_claim_name: kid
#      claims_to_verify:
#        - exp

# Consumers
consumers:
  - username: login_identity_issuer
    custom_id: login_identity_issuer

# Config plugins
jwt_secrets:
  - consumer: login_identity_issuer
    secret: "Evvwju8QwXGOeACgCD65U4i0X2q8qL++/I1zso3wDnc="
