_format_version: "3.0"
_transform: true

services:
  - host: sample-service
    name: sample_api_service
    port: 80
    protocol: http
    routes:
      - name: path_mocks
        paths:
          - /mocks
        strip_path: true

  - host: sample-identity-service
    name: sample_identity_api_service
    port: 80
    protocol: http
    routes:
      - name: path_identity
        paths:
          - /identity
        strip_path: true

plugins:
  - name: jwt
    service: sample_identity_api_service
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    service: sample_api_service
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp

consumers:
  - username: login_identity_issuer
    custom_id: login_identity_issuer

jwt_secrets:
  - consumer: login_identity_issuer
    secret: "Evvwju8QwXGOeACgCD65U4i0X2q8qL++/I1zso3wDnc="
