version: '3.7'

services:
  mentee_service:
    build:
      context: mentee
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mentor_service:
    build:
      context: mentor
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  nginx_gateway:
    image: nginx
    ports:
      - 9000:80
      - 9001:443
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/cert:/var/www/cert
